/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.swinglocadora.view;

import com.mycompany.swinglocadora.controller.AtorController;
import com.mycompany.swinglocadora.db.DbException;
import com.mycompany.swinglocadora.model.entities.Ator;
import com.mycompany.swinglocadora.model.exceptions.ValidationException;
import java.util.Set;
import javax.swing.JOptionPane;

public class TelaCadastroAtor extends javax.swing.JFrame {
    
    private TelaPrincipal telaPrincipal;
    
    /**
     * Creates new form TelaCadastroAtor
     */
    public TelaCadastroAtor(TelaPrincipal tela) {
        initComponents();
        this.telaPrincipal = tela;
        jButtonDeletar.setVisible(false);
        this.ator = new Ator();
        atorController = new AtorController();
    }
    
    public void carregaAtor(Ator ator) {
        this.ator = ator;
        jTextFieldNome.setText(ator.getNome());
        jComboBoxNacionalidade.setSelectedItem(ator.getNacionalidade());
        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.png"))); // NOI18N
        jLabelTitulo.setText("Editando o Ator: Cod " + this.ator.getId_ator()); 
        jButtonDeletar.setVisible(true);
    }
    
    // Usado ao fechar a tela de consulta
    public void atorNull() {
        this.ator = null;
        jTextFieldNome.setText("");
        jLabelErrorNome.setText("");
        jLabelTitulo.setText("Cadastro de Ator"); 
        jButtonDeletar.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelCaddastroAtor = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelNacionalidade = new javax.swing.JLabel();
        jComboBoxNacionalidade = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtionCancelar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jLabelErrorNome = new javax.swing.JLabel();
        jButtonDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Video Locadora Hora da Pipoca");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                fecharJanela(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.png"))); // NOI18N
        jLabelTitulo.setText("Cadastro de Ator");

        jPanelCaddastroAtor.setBackground(new java.awt.Color(102, 102, 102));

        jLabelNome.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome:");

        jTextFieldNome.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabelNacionalidade.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNacionalidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNacionalidade.setText("Nacionalidade:");

        jComboBoxNacionalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brasileiro", "Argentino", "Espanhol", "Inglês", "Americano", "Alemão", "Japonês", " " }));

        jButtonSalvar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtionCancelar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtionCancelar.setText("Cancelar");
        jButtionCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtionCancelarActionPerformed(evt);
            }
        });

        jButtonConsultar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jLabelErrorNome.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelErrorNome.setForeground(new java.awt.Color(255, 51, 51));

        jButtonDeletar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonDeletar.setText("Deletar");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCaddastroAtorLayout = new javax.swing.GroupLayout(jPanelCaddastroAtor);
        jPanelCaddastroAtor.setLayout(jPanelCaddastroAtorLayout);
        jPanelCaddastroAtorLayout.setHorizontalGroup(
            jPanelCaddastroAtorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaddastroAtorLayout.createSequentialGroup()
                .addGroup(jPanelCaddastroAtorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCaddastroAtorLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButtonSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtionCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeletar))
                    .addGroup(jPanelCaddastroAtorLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanelCaddastroAtorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCaddastroAtorLayout.createSequentialGroup()
                                .addComponent(jLabelNacionalidade)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCaddastroAtorLayout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelErrorNome)))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanelCaddastroAtorLayout.setVerticalGroup(
            jPanelCaddastroAtorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaddastroAtorLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelCaddastroAtorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelErrorNome))
                .addGap(26, 26, 26)
                .addGroup(jPanelCaddastroAtorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNacionalidade)
                    .addComponent(jComboBoxNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanelCaddastroAtorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtionCancelar)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButtonDeletar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanelCaddastroAtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabelTitulo)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelTitulo)
                .addGap(30, 30, 30)
                .addComponent(jPanelCaddastroAtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldNome.setText("");
        jLabelErrorNome.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (this.ator == null) this.ator = new Ator();
        String nacionalidade = jComboBoxNacionalidade.getSelectedItem().toString();
        
        this.ator.setNome(jTextFieldNome.getText());
        this.ator.setNacionalidade(nacionalidade);
        try {
            Integer id = this.ator.getId_ator();
            atorController.save(this.ator);
            if (id == null) {
                JOptionPane.showMessageDialog(null, "Ator cadastrado com sucesso");           
            } else {
                JOptionPane.showMessageDialog(null, "Ator atualizado com sucesso");           
            }
            this.jButtonLimparActionPerformed(evt);
            this.ator = new Ator();
         
        } catch (ValidationException e) {
            Set<String> fields = e.getErrors().keySet();
		
            if (fields.contains("nome")) {
		jLabelErrorNome.setText(e.getErrors().get("nome"));
            }
        } catch(DbException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        TelaListaAtor telaListaAtor = new TelaListaAtor(this);
        this.setVisible(false);
        telaListaAtor.setVisible(true);
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        if (this.ator == null) {
            JOptionPane.showMessageDialog(null, "Selecione um ator para deletar");
            return;
        }
        
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente apagar o ator?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resposta != JOptionPane.YES_OPTION) return;
        
        try {
            this.atorController.delete(this.ator);
            this.atorNull();
            JOptionPane.showMessageDialog(null, "Ator deletado com sucesso");
        } catch(DbException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtionCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtionCancelarActionPerformed
        this.dispose();
        this.telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtionCancelarActionPerformed

    private void fecharJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fecharJanela
        this.dispose();
        this.telaPrincipal.setVisible(true);
    }//GEN-LAST:event_fecharJanela

    // Meus atributos
    private AtorController atorController;
    private Ator ator;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtionCancelar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxNacionalidade;
    private javax.swing.JLabel jLabelErrorNome;
    private javax.swing.JLabel jLabelNacionalidade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelCaddastroAtor;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
